# Generated by Django 4.1.7 on 2023-03-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_card_last_4_digits',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_payments_method_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
