# Generated by Django 4.1.7 on 2023-03-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_pickup_address_job_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pickup_address',
            field=models.CharField(blank=True, default='job address', max_length=300),
        ),
    ]
