# Generated by Django 4.1.7 on 2023-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivery_address',
            field=models.CharField(blank=True, default='delivery address', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_longtitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
