# Generated by Django 4.1.7 on 2023-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='courier',
            name='fcm_token',
            field=models.TextField(blank=True),
        ),
    ]
